version: '3.7'
services:
    flask:
        build: .
        command: python /app/app.py
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis:5.0.7
        ports:
            - "6379:6379"
    celery:
        build: .
        command: celery worker -A /app/app.celery
        depends_on:
            - redis
            - flask
