version: '3.7'
services:
    flask:
        build: .
        command: python app/app.py
        ports:
            - "5000:5000"
        depends_on:
            - redis
    redis:
        image: redis:5.0.7
        ports:
            - "6379:6379"
    celery:
        build: .
        command: cd \app && celery -A app.celery worker
        depends_on:
            - redis
            - flask
